"""empty message

Revision ID: 2f75ea619b36
Revises: 9e1290222342
Create Date: 2023-09-22 15:06:42.790421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f75ea619b36'
down_revision = '9e1290222342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EngineeredWoodCoverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(length=200), nullable=False),
    sa.Column('width_ft', sa.Float(), nullable=False),
    sa.Column('length_ft', sa.Float(), nullable=False),
    sa.Column('thickness_mm', sa.Float(), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=False),
    sa.Column('volume_cuft', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EngineeredWoodCoverage')
    # ### end Alembic commands ###
