"""empty message

Revision ID: 73d3c2a268bf
Revises: c669597e79ee
Create Date: 2023-09-22 15:01:16.700849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d3c2a268bf'
down_revision = 'c669597e79ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EngineeredWoodCoverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('material', sa.String(length=200), nullable=False),
    sa.Column('width_ft', sa.Float(), nullable=False),
    sa.Column('length_ft', sa.Float(), nullable=False),
    sa.Column('thickness_mm', sa.Float(), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=False),
    sa.Column('volume_cuft', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EngineeredWoodCoverage')
    # ### end Alembic commands ###
