"""empty message

Revision ID: c669597e79ee
Revises: 2c24c6d51e70
Create Date: 2023-09-11 14:36:58.380127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c669597e79ee'
down_revision = '2c24c6d51e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MaterialPrice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=200), nullable=False),
    sa.Column('ave_price_luzon', sa.Float(), nullable=False),
    sa.Column('ave_price_visayas', sa.Float(), nullable=False),
    sa.Column('ave_price_mindanao', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MaterialPrice')
    # ### end Alembic commands ###
