"""empty message

Revision ID: c90783ac18e2
Revises: 
Create Date: 2023-08-03 15:31:58.134824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90783ac18e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DataSource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Ref', sa.String(length=200), nullable=False),
    sa.Column('Status', sa.String(length=250), nullable=False),
    sa.Column('Location', sa.String(length=250), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=False),
    sa.Column('Created', sa.String(length=250), nullable=False),
    sa.Column('Type', sa.String(length=250), nullable=False),
    sa.Column('Status_Changed', sa.String(length=250), nullable=False),
    sa.Column('Open_Actions', sa.String(length=250), nullable=False),
    sa.Column('Total_Actions', sa.String(length=250), nullable=False),
    sa.Column('Association', sa.String(length=250), nullable=True),
    sa.Column('OverDue', sa.String(length=250), nullable=False),
    sa.Column('Images', sa.String(length=250), nullable=False),
    sa.Column('Comments', sa.String(length=250), nullable=False),
    sa.Column('Documents', sa.String(length=250), nullable=False),
    sa.Column('Project', sa.String(length=250), nullable=False),
    sa.Column('Report_Forms_Status', sa.String(length=250), nullable=False),
    sa.Column('Report_Forms_Group', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DataSource')
    # ### end Alembic commands ###
