"""empty message

Revision ID: de08708154f8
Revises: 
Create Date: 2023-09-05 15:08:22.135777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de08708154f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conversion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversion_type', sa.String(length=200), nullable=False),
    sa.Column('to_convert', sa.String(length=200), nullable=False),
    sa.Column('meter', sa.Float(), nullable=True),
    sa.Column('centimeter', sa.Float(), nullable=True),
    sa.Column('millimeter', sa.Float(), nullable=True),
    sa.Column('foot', sa.Float(), nullable=True),
    sa.Column('inch', sa.Float(), nullable=True),
    sa.Column('kilometer', sa.Float(), nullable=True),
    sa.Column('mile', sa.Float(), nullable=True),
    sa.Column('hectare', sa.Float(), nullable=True),
    sa.Column('yard', sa.Float(), nullable=True),
    sa.Column('liter', sa.Float(), nullable=True),
    sa.Column('milliliter', sa.Float(), nullable=True),
    sa.Column('quarts', sa.Float(), nullable=True),
    sa.Column('board_foot', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DataSource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Ref', sa.String(length=200), nullable=False),
    sa.Column('Status', sa.String(length=250), nullable=False),
    sa.Column('Location', sa.String(length=250), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=False),
    sa.Column('Created', sa.String(length=250), nullable=False),
    sa.Column('Type', sa.String(length=250), nullable=False),
    sa.Column('Status_Changed', sa.String(length=250), nullable=False),
    sa.Column('Open_Actions', sa.String(length=250), nullable=False),
    sa.Column('Total_Actions', sa.String(length=250), nullable=False),
    sa.Column('Association', sa.String(length=250), nullable=True),
    sa.Column('OverDue', sa.String(length=250), nullable=False),
    sa.Column('Images', sa.String(length=250), nullable=False),
    sa.Column('Comments', sa.String(length=250), nullable=False),
    sa.Column('Documents', sa.String(length=250), nullable=False),
    sa.Column('Project', sa.String(length=250), nullable=False),
    sa.Column('Report_Forms_Status', sa.String(length=250), nullable=False),
    sa.Column('Report_Forms_Group', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MassWeightConversion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_convert', sa.String(length=200), nullable=False),
    sa.Column('kilogram', sa.Float(), nullable=True),
    sa.Column('gram', sa.Float(), nullable=True),
    sa.Column('milligram', sa.Float(), nullable=True),
    sa.Column('metric_ton', sa.Float(), nullable=True),
    sa.Column('long_ton', sa.Float(), nullable=True),
    sa.Column('short_ton', sa.Float(), nullable=True),
    sa.Column('pound', sa.Float(), nullable=True),
    sa.Column('ounce', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MassWeightConversion')
    op.drop_table('DataSource')
    op.drop_table('Conversion')
    # ### end Alembic commands ###
