"""empty message

Revision ID: f8bd81e7ec9f
Revises: de08708154f8
Create Date: 2023-09-05 16:37:27.278195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bd81e7ec9f'
down_revision = 'de08708154f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Conversion', sa.Column('gallons', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Conversion', 'gallons')
    # ### end Alembic commands ###
